# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'memoirs' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for memoirs
  pod 'Nuke', '~> 7.0'
  pod 'Alamofire', '~> 5.0.0-beta.3'

end
